import { Injectable } from '@nestjs/common';
import { AiVisionInput } from '../ai.types';

@Injectable()
export class VisionAnalysisPromptBuilder {
  buildContext(input: AiVisionInput): string {
    const { dto, detectedLanguage, translationLanguage } = input;

    return [
      'You are analyzing an X/Twitter post with text and image context.',
      '',
      `Platform: ${dto.post.platform}`,
      `Detected language: ${detectedLanguage}`,
      `Explanation/translation language: ${translationLanguage}`,
      `Niche: ${dto.options.niche}`,
      `Author name: ${dto.post.authorName ?? ''}`,
      `Author handle: ${dto.post.authorHandle ?? ''}`,
      `Post URL: ${dto.post.url ?? ''}`,
      '',
      'Attached image metadata:',
      ...input.images.map((image, index) =>
        [
          `Image ${index + 1}:`,
          `- Source URL: ${image.sourceUrl}`,
          `- Content type: ${image.contentType}`,
          `- Alt text: ${image.altText ?? ''}`,
        ].join('\n'),
      ),
      '',
      'Your job:',
      '1. Understand the post text.',
      '2. Understand the attached image or images.',
      '3. Explain how the image supports, changes, or contradicts the post text.',
      '4. Extract visible text from the image if present.',
      '5. Identify the safest and most natural comment angle.',
      '6. Do not generate comment suggestions in this step.',
      '',
      'Return valid JSON with this exact shape:',
      '{',
      '  "translation": string,',
      '  "summary": string,',
      '  "context": string,',
      '  "theme": string,',
      '  "topic": string,',
      '  "sentiment": string,',
      '  "commentStrategy": string,',
      '  "imageAnalysis": {',
      '    "summary": string,',
      '    "visibleText": string,',
      '    "visualTone": string,',
      '    "importantObjects": string[],',
      '    "uncertainty": string',
      '  },',
      '  "combinedContext": {',
      '    "topic": string,',
      '    "intent": string,',
      '    "sentiment": string,',
      '    "explanation": string,',
      '    "commentStrategy": string,',
      '    "avoid": string[]',
      '  }',
      '}',
      '',
      'Rules:',
      '- Output JSON only, with no markdown.',
      '- Do not make claims that are not supported by the post or image.',
      '- If the image is unclear, write the uncertainty clearly.',
      '- If visible text is unreadable, say it is unreadable.',
      '- Write translation, summary, context, commentStrategy, imageAnalysis, and combinedContext in the explanation/translation language.',
      '',
      `Post text:\n${dto.post.text}`,
    ].join('\n');
  }

  build(input: AiVisionInput): string {
    const { dto, detectedLanguage, targetLanguage, translationLanguage } = input;

    return [
      'You are analyzing an X/Twitter post with text and image context.',
      '',
      `Platform: ${dto.post.platform}`,
      `Detected language: ${detectedLanguage}`,
      `Explanation/translation language: ${translationLanguage}`,
      `Target comment language: ${targetLanguage}`,
      `Tone: ${dto.options.tone}`,
      `Niche: ${dto.options.niche}`,
      `Max suggestions: ${dto.options.maxSuggestions}`,
      `Author name: ${dto.post.authorName ?? ''}`,
      `Author handle: ${dto.post.authorHandle ?? ''}`,
      `Post URL: ${dto.post.url ?? ''}`,
      '',
      'Attached image metadata:',
      ...input.images.map((image, index) =>
        [
          `Image ${index + 1}:`,
          `- Source URL: ${image.sourceUrl}`,
          `- Content type: ${image.contentType}`,
          `- Alt text: ${image.altText ?? ''}`,
        ].join('\n'),
      ),
      '',
      'Your job:',
      '1. Understand the post text.',
      '2. Understand the attached image or images.',
      '3. Explain how the image supports, changes, or contradicts the post text.',
      '4. Extract visible text from the image if present.',
      '5. Identify the safest and most natural comment angle.',
      '6. Generate short, native-like comments in the requested target comment language.',
      '',
      'Return valid JSON with this exact shape:',
      '{',
      '  "translation": string,',
      '  "summary": string,',
      '  "context": string,',
      '  "theme": string,',
      '  "topic": string,',
      '  "sentiment": string,',
      '  "commentStrategy": string,',
      '  "imageAnalysis": {',
      '    "summary": string,',
      '    "visibleText": string,',
      '    "visualTone": string,',
      '    "importantObjects": string[],',
      '    "uncertainty": string',
      '  },',
      '  "combinedContext": {',
      '    "topic": string,',
      '    "intent": string,',
      '    "sentiment": string,',
      '    "explanation": string,',
      '    "commentStrategy": string,',
      '    "avoid": string[]',
      '  },',
      '  "suggestions": [',
      '    {',
      '      "text": string,',
      '      "meaningVi": string,',
      '      "tone": string,',
      '      "risk": "low" | "medium" | "high",',
      '      "whyItWorks": string',
      '    }',
      '  ]',
      '}',
      '',
      'Rules:',
      '- Output JSON only, with no markdown.',
      '- Do not make claims that are not supported by the post or image.',
      '- If the image is unclear, write the uncertainty clearly.',
      '- If visible text is unreadable, say it is unreadable.',
      '- Avoid generic replies like Great post or Nice.',
      '- Keep suggestions short and natural for X/Twitter.',
      '- Write translation, summary, context, commentStrategy, imageAnalysis, and combinedContext in the explanation/translation language.',
      '- meaningVi must always be Vietnamese.',
      '',
      `Post text:\n${dto.post.text}`,
    ].join('\n');
  }
}
