import type { NicheSignalDefinition } from '../niche.types';
import { any, ja, vi } from './kw';

export const AI_ML_SIGNALS: NicheSignalDefinition = {
  niche: 'ai_ml',
  version: '1.0.0',
  strong: [
    any('llm', /\b(llm|large language model)s?\b/),
    any('chatgpt', /\b(chatgpt|gpt-?[45]|o[34]-mini)\b/),
    any('claude', /\bclaude\s*(opus|sonnet|haiku|code)?\b/),
    any('gemini', /\bgemini\s*(pro|flash|\d)/),
    any('transformer', /\btransformer(s|\sarchitecture)?\b/),
    any('rag', /\b(rag|retrieval[- ]augmented)\b/),
    any('fine-tuning', /\bfine[- ]?tun(e|ed|ing)\b/),
    any('embeddings', /\bembedding(s|\smodel)\b/),
    any('prompt-engineering', /\bprompt engineering\b/),
    any('ai-agent', /\bai agents?\b/),
    any('machine-learning', /\bmachine learning\b/),
    any('neural-network', /\bneural net(work)?s?\b/),
    any('diffusion', /\b(stable diffusion|diffusion model)\b/),
    any('lab', /\b(openai|anthropic|deepmind|mistral ai|hugging ?face)\b/),
    any('inference', /\binference (cost|latency|endpoint)\b/),
    vi('tri-tue-nhan-tao', /trí tuệ nhân tạo/),
    vi('hoc-may', /học máy|mô hình ngôn ngữ/),
    ja('seisei-ai', /生成ai|大規模言語モデル/),
    ja('kikai-gakushu', /機械学習|ディープラーニング/),
  ],
  weak: [
    any('ai', /\bai\b/),
    any('model', /\bmodels?\b/),
    any('dataset', /\bdatasets?\b/),
    any('training', /\btraining\b/),
    any('gpu', /\b(gpu|h100|cuda)\b/),
    any('tokens', /\btokens?\/s|\bcontext window\b/),
    any('benchmark', /\bbenchmarks?\b/),
    vi('mo-hinh', /mô hình/),
    ja('moderu', /モデル|推論/),
  ],
  hashtagAliases: [
    'ai',
    'aiml',
    'ai_ml',
    'llm',
    'llms',
    'genai',
    'machinelearning',
    'deeplearning',
    'aiagents',
    'openai',
    'chatgpt',
  ],
  cashtags: [],
  domains: ['huggingface.co', 'openai.com', 'anthropic.com', 'ollama.com'],
};
