import type { NicheSignalDefinition } from '../niche.types';
import { any, en, ja, vi } from './kw';

export const CRYPTO_SIGNALS: NicheSignalDefinition = {
  niche: 'crypto',
  version: '1.0.0',
  strong: [
    any('bitcoin', /\b(bitcoin|btc)\b/),
    any('ethereum', /\b(ethereum|eth)\b/),
    any('solana', /\b(solana|sol)\b/),
    any('blockchain', /\bblockchain\b/),
    any('defi', /\b(defi|dex|amm|liquidity pool)\b/),
    any('web3', /\bweb ?3\b/),
    any('nft', /\bnfts?\b/),
    any('airdrop', /\bairdrops?\b/),
    any('staking', /\b(staking|validator|slashing)\b/),
    any('onchain', /\bon[- ]?chain\b/),
    any('wallet', /\b(metamask|phantom wallet|cold wallet|seed phrase)\b/),
    any('memecoin', /\b(memecoin|shitcoin|altcoins?)\b/),
    any('tokenomics', /\btokenomics\b/),
    vi('tien-dien-tu', /tiền điện tử|tiền ảo|sàn giao dịch coin/),
    ja('kasou-tsuuka', /仮想通貨|暗号資産/),
  ],
  weak: [
    en('token', /\btokens?\b/),
    en('chain', /\bchains?\b/),
    en('mint', /\bmint(ed|ing)?\b/),
    en('pump', /\b(pump|dump|hodl|degen)\b/),
    en('market-cap', /\bmarket cap\b/),
    ja('coin', /コイン|取引所/),
  ],
  hashtagAliases: [
    'crypto',
    'cryptocurrency',
    'bitcoin',
    'btc',
    'ethereum',
    'eth',
    'solana',
    'web3',
    'defi',
    'nft',
    'altcoin',
  ],
  cashtags: ['BTC', 'ETH', 'SOL', 'BNB', 'XRP', 'ADA', 'DOGE', 'AVAX'],
  domains: [
    'binance.com',
    'coinbase.com',
    'coingecko.com',
    'dexscreener.com',
    'etherscan.io',
    'opensea.io',
  ],
};
