import type { NicheSignalDefinition } from '../niche.types';
import { any, en, ja, vi } from './kw';

export const TECH_SIGNALS: NicheSignalDefinition = {
  niche: 'tech',
  version: '1.0.0',
  strong: [
    any('typescript', /\b(typescript|javascript)\b/),
    any('framework', /\b(react|next\.?js|vue|svelte|angular)\b/),
    any('language', /\b(python|rust|golang|kotlin|swift)\b/),
    any('infra', /\b(kubernetes|k8s|docker|terraform)\b/),
    any('database', /\b(postgres(ql)?|mysql|mongodb|redis|sqlite)\b/),
    en('api-design', /\b(rest api|graphql|grpc|webhook)s?\b/),
    en('layer', /\b(backend|frontend|full[- ]stack|devops)\b/),
    en('open-source', /\bopen[- ]source\b/),
    en('refactor', /\brefactor(ing|ed)?\b/),
    en('ci-cd', /\b(ci\/cd|pipeline fail|merge conflict)\b/),
    en('compiler', /\b(compiler|runtime|type system)\b/),
    vi('lap-trinh', /lập trình|mã nguồn|phần mềm/),
    ja('kaihatsu', /プログラミング|開発者|エンジニア/),
  ],
  weak: [
    en('code', /\bcode\b/),
    en('bug', /\bbugs?\b/),
    en('build', /\bbuilds?\b/),
    en('server', /\bservers?\b/),
    en('library', /\b(librar(y|ies)|framework)\b/),
    en('deploy', /\bdeploy(ed|ing|ment)?\b/),
    vi('cong-nghe', /công nghệ/),
    ja('kaihatsu-weak', /開発|コード/),
  ],
  hashtagAliases: [
    'tech',
    'technology',
    'coding',
    'programming',
    'webdev',
    'devops',
    'opensource',
    'softwareengineering',
    'typescript',
    'javascript',
    'python',
  ],
  cashtags: [],
  domains: [
    'github.com',
    'gitlab.com',
    'stackoverflow.com',
    'npmjs.com',
    'vercel.com',
    'developer.mozilla.org',
  ],
};
